/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.SupplierItem;

import application.controller.SupplierItemController;
import application.entity.SupplierItem;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class SupplierItemView extends javax.swing.JDialog {

    /**
     * Creates new form SupplierItemView
     */
    public DefaultTableModel modelSupplierItem;
    private SupplierItemController supplierItemController = null;
    private TableColumnModel tcmSupplierItem;
    private TableColumn colSupplierItemId;
    private TableColumnModel columnModels;
    private SupplierItem supplierItem;
    
    public SupplierItemView(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        
        columnModels = tblSupplierItem.getColumnModel();
        modelSupplierItem = (DefaultTableModel) tblSupplierItem.getModel();
        supplierItemController = new SupplierItemController();
        supplierItemController.getAllSupplierItems(modelSupplierItem);
        tcmSupplierItem = tblSupplierItem.getColumnModel();
        colSupplierItemId = tcmSupplierItem.getColumn(0);
        tcmSupplierItem.removeColumn(colSupplierItemId);
        checkBtnSupplierItem();
        txtSupplierItemSearch.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSupplierItemSearch = new javax.swing.JTextField();
        btnSupplierItemDelete = new javax.swing.JButton();
        btnSupplierItemAdd = new javax.swing.JButton();
        btnSupplierItemUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supplier Item View");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Search");

        txtSupplierItemSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierItemSearchKeyReleased(evt);
            }
        });

        btnSupplierItemDelete.setText("Delete");
        btnSupplierItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierItemDeleteActionPerformed(evt);
            }
        });

        btnSupplierItemAdd.setText("Add");
        btnSupplierItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierItemAddActionPerformed(evt);
            }
        });

        btnSupplierItemUpdate.setText("Update");
        btnSupplierItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierItemUpdateActionPerformed(evt);
            }
        });

        tblSupplierItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplierItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplierItem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSupplierItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSupplierItemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSupplierItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSupplierItemSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSupplierItemSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupplierItemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupplierItemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupplierItemAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplierItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierItemAddActionPerformed
          //Add button in Supplier Item view
        SupplierItemAdd supplierItemAddAdd = new SupplierItemAdd(this, true, this);
        supplierItemAddAdd.setVisible(true);
        supplierItemController.getAllSupplierItems(modelSupplierItem);
        checkBtnSupplierItem();
    }//GEN-LAST:event_btnSupplierItemAddActionPerformed

    private void tblSupplierItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierItemMouseClicked
      checkBtnSupplierItem();
    }//GEN-LAST:event_tblSupplierItemMouseClicked

    private void txtSupplierItemSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierItemSearchKeyReleased
       // TODO add your handling code here:
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelSupplierItem);
        tblSupplierItem.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtSupplierItemSearch.getText()));
        checkBtnSupplierItem();
//        in here "?!" act as "like" operator in sql 
    }//GEN-LAST:event_txtSupplierItemSearchKeyReleased

    private void btnSupplierItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierItemDeleteActionPerformed
           //Delete buttton action

        int status = JOptionPane.showConfirmDialog(this, "Do you want to delete these Supplier Items ?", "Delete Product", JOptionPane.YES_NO_OPTION);
        if (status == JOptionPane.YES_OPTION) {
            int selectedRow = tblSupplierItem.convertRowIndexToModel(tblSupplierItem.getSelectedRow());
            int supplierItemId = Integer.valueOf(modelSupplierItem.getValueAt(selectedRow, 0).toString());
            SupplierItem supplierItem = supplierItemController.findSupplierItemById(supplierItemId);
            supplierItem.setStatus(false);
            supplierItem.setDeletedAt(new Date());
            if (supplierItemController.update(supplierItem)) {
                modelSupplierItem.removeRow(selectedRow);
                 checkBtnSupplierItem();
                JOptionPane.showMessageDialog(this, "Supplier Items deleted Successfully.", "Deletion Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error in Deleting Supplier Items.", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        txtSupplierItemSearch.requestFocus();

    }//GEN-LAST:event_btnSupplierItemDeleteActionPerformed

    private void btnSupplierItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierItemUpdateActionPerformed
         //Update button action
        int selectedRow = tblSupplierItem.convertRowIndexToModel(tblSupplierItem.getSelectedRow());

        SupplierItemUpdate repairUpdate = new SupplierItemUpdate(this, true);
        SupplierItem supplierItem = new SupplierItem();
        supplierItem.setSupplierItemId(Integer.valueOf(modelSupplierItem.getValueAt(selectedRow, 0).toString()));
        supplierItem.setSupplierItemManufacturer(modelSupplierItem.getValueAt(selectedRow, 1).toString());
        supplierItem.setSupplierItemDescription(modelSupplierItem.getValueAt(selectedRow, 2).toString());
        supplierItem.setSupplierItemUOM(modelSupplierItem.getValueAt(selectedRow, 3).toString());
        String supplier = supplierItem.getSupplierRef().toString();
        SupplierItemUpdate supplierItemUpdate = new SupplierItemUpdate(null, rootPaneCheckingEnabled);
        //supplierItemUpdate.setSupplierItemUpdate(supplierItem, supplier);
        supplierItemUpdate.setSupplierItemUpdate(supplierItem);
        repairUpdate.setVisible(true);
        supplierItemController.getAllSupplierItems(modelSupplierItem);
        checkBtnSupplierItem();
        txtSupplierItemSearch.requestFocus();
    }//GEN-LAST:event_btnSupplierItemUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SupplierItemView dialog = new SupplierItemView(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSupplierItemAdd;
    private javax.swing.JButton btnSupplierItemDelete;
    private javax.swing.JButton btnSupplierItemUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplierItem;
    private javax.swing.JTextField txtSupplierItemSearch;
    // End of variables declaration//GEN-END:variables
 private void checkBtnSupplierItem() {
        if (tblSupplierItem.getSelectedRowCount() > 0) {
            btnSupplierItemDelete.setEnabled(true);
            btnSupplierItemUpdate.setEnabled(true);
        } else {
            btnSupplierItemDelete.setEnabled(false);
            btnSupplierItemUpdate.setEnabled(false);
        }
    }
}
