package application.Dashbord;

import application.forms.po.POView;
import application.view.product.productView;
import application.forms.GRN.GRNMain;
import application.forms.po.POAccept1;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.Date;
import tabs.ui.CWTabbedPaneUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shashiprabha
 */
public class Dashbord extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Dashbord() {
        initComponents();
        setLocationRelativeTo(this);

        //      DateTime function        
        getDateAndTime();

        LocalDateTime now = LocalDateTime.now();
        int year = now.getYear();
        Month month = now.getMonth();
        int day = now.getDayOfMonth();
        int hour = now.getHour();
        int minute = now.getMinute();
        dayLable.setText(month + "  " + Integer.toString(day) + "," + Integer.toString(year));

        jTabbedPane1.setUI(new CWTabbedPaneUI());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timeLable = new javax.swing.JLabel();
        dayLable = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSystem = new javax.swing.JPanel();
        btnSupplier = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnRequisition = new javax.swing.JButton();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        pnlProduct = new javax.swing.JPanel();
        btnProduct = new javax.swing.JButton();
        btnProductCategory = new javax.swing.JButton();
        lblImage4 = new javax.swing.JLabel();
        lblImage3 = new javax.swing.JLabel();
        lblImage5 = new javax.swing.JLabel();
        btnProductCount = new javax.swing.JButton();
        pnlPo = new javax.swing.JPanel();
        btnPo = new javax.swing.JButton();
        lblImage6 = new javax.swing.JLabel();
        lblImage7 = new javax.swing.JLabel();
        btnPoAccept = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlGrn = new javax.swing.JPanel();
        btnGrn = new javax.swing.JButton();
        btnGrnCount = new javax.swing.JButton();
        lblImage8 = new javax.swing.JLabel();
        lblImage9 = new javax.swing.JLabel();
        lblImage10 = new javax.swing.JLabel();
        pnlInvoice = new javax.swing.JPanel();
        btnPayment = new javax.swing.JButton();
        btnInvoice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        timeLable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeLable.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(timeLable);
        timeLable.setBounds(660, 620, 290, 30);

        dayLable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dayLable.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dayLable);
        dayLable.setBounds(660, 580, 290, 30);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1024, 720));

        pnlSystem.setOpaque(false);

        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supplier2.png"))); // NOI18N
        btnSupplier.setPreferredSize(new java.awt.Dimension(140, 140));

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User.png"))); // NOI18N

        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employee2.png"))); // NOI18N

        btnRequisition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/requisition.png"))); // NOI18N
        btnRequisition.setOpaque(false);

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img1.png"))); // NOI18N

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img2.png"))); // NOI18N

        javax.swing.GroupLayout pnlSystemLayout = new javax.swing.GroupLayout(pnlSystem);
        pnlSystem.setLayout(pnlSystemLayout);
        pnlSystemLayout.setHorizontalGroup(
            pnlSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSystemLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblImage1)
                .addGap(8, 8, 8)
                .addGroup(pnlSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSystemLayout.createSequentialGroup()
                        .addComponent(lblImage2)
                        .addGap(8, 8, 8)
                        .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnRequisition, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        pnlSystemLayout.setVerticalGroup(
            pnlSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSystemLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSystemLayout.createSequentialGroup()
                        .addGroup(pnlSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImage1)
                            .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(lblImage2))
                    .addComponent(btnRequisition, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("System", pnlSystem);

        pnlProduct.setOpaque(false);

        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Product.png"))); // NOI18N
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        btnProductCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/category.png"))); // NOI18N

        lblImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img3.png"))); // NOI18N

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img4.png"))); // NOI18N

        lblImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img5.png"))); // NOI18N

        btnProductCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Product-Count.png"))); // NOI18N
        btnProductCount.setPreferredSize(new java.awt.Dimension(140, 140));

        javax.swing.GroupLayout pnlProductLayout = new javax.swing.GroupLayout(pnlProduct);
        pnlProduct.setLayout(pnlProductLayout);
        pnlProductLayout.setHorizontalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductLayout.createSequentialGroup()
                .addGroup(pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lblImage4)
                        .addGap(8, 8, 8)
                        .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImage5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProductCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblImage3)
                .addGap(8, 8, 8)
                .addComponent(btnProductCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        pnlProductLayout.setVerticalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductLayout.createSequentialGroup()
                .addGroup(pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblImage4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProductCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblImage3)
                        .addComponent(btnProductCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage5)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Product", pnlProduct);

        pnlPo.setOpaque(false);

        btnPo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Po.png"))); // NOI18N
        btnPo.setOpaque(false);
        btnPo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoActionPerformed(evt);
            }
        });

        lblImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img6.png"))); // NOI18N

        lblImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img7.png"))); // NOI18N

        btnPoAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Accept (2).png"))); // NOI18N
        btnPoAccept.setOpaque(false);
        btnPoAccept.setPreferredSize(new java.awt.Dimension(140, 140));
        btnPoAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoAcceptActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 50, 136));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 140));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("21");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PO COUNT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlPoLayout = new javax.swing.GroupLayout(pnlPo);
        pnlPo.setLayout(pnlPoLayout);
        pnlPoLayout.setHorizontalGroup(
            pnlPoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoLayout.createSequentialGroup()
                .addGroup(pnlPoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPoLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnPo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblImage6))
                    .addGroup(pnlPoLayout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImage7)
                        .addGap(18, 18, 18)
                        .addComponent(btnPoAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlPoLayout.setVerticalGroup(
            pnlPoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlPoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage6))
                .addGap(8, 8, 8)
                .addGroup(pnlPoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage7)
                    .addComponent(btnPoAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(344, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Purchase Order", pnlPo);

        pnlGrn.setOpaque(false);

        btnGrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grn.png"))); // NOI18N
        btnGrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrnActionPerformed(evt);
            }
        });

        btnGrnCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grn-count.png"))); // NOI18N
        btnGrnCount.setPreferredSize(new java.awt.Dimension(140, 140));

        lblImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img8.png"))); // NOI18N

        lblImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img9.png"))); // NOI18N

        lblImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img11.png"))); // NOI18N

        javax.swing.GroupLayout pnlGrnLayout = new javax.swing.GroupLayout(pnlGrn);
        pnlGrn.setLayout(pnlGrnLayout);
        pnlGrnLayout.setHorizontalGroup(
            pnlGrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrnLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(lblImage8)
                .addGap(8, 8, 8)
                .addGroup(pnlGrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGrnLayout.createSequentialGroup()
                        .addComponent(lblImage10)
                        .addGap(8, 8, 8)
                        .addComponent(btnGrnCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblImage9))
                    .addComponent(btnGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        pnlGrnLayout.setVerticalGroup(
            pnlGrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrnLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlGrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage8))
                .addGap(8, 8, 8)
                .addGroup(pnlGrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrnCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage10)
                    .addComponent(lblImage9))
                .addContainerGap(344, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Good Receiving", pnlGrn);

        pnlInvoice.setOpaque(false);

        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment.png"))); // NOI18N

        btnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/invoice.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img13.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img12.png"))); // NOI18N

        javax.swing.GroupLayout pnlInvoiceLayout = new javax.swing.GroupLayout(pnlInvoice);
        pnlInvoice.setLayout(pnlInvoiceLayout);
        pnlInvoiceLayout.setHorizontalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(btnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInvoiceLayout.setVerticalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(344, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Invoice", pnlInvoice);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1024, 720);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back-dash.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 30, 1030, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        productView view = new productView(this, rootPaneCheckingEnabled);
        view.setVisible(true);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnPoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoActionPerformed
     POView poView = new POView(this, rootPaneCheckingEnabled);
     poView.setVisible(true);
     
    }//GEN-LAST:event_btnPoActionPerformed

    private void btnGrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrnActionPerformed
        // TODO add your handling code here:
        GRNMain grnm = new GRNMain(this, rootPaneCheckingEnabled);
        grnm.setVisible(true);
    }//GEN-LAST:event_btnGrnActionPerformed

    private void btnPoAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoAcceptActionPerformed
        POAccept1 accept1 = new POAccept1(this, rootPaneCheckingEnabled);
        accept1.setVisible(true);
    }//GEN-LAST:event_btnPoAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnGrn;
    private javax.swing.JButton btnGrnCount;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnPo;
    private javax.swing.JButton btnPoAccept;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnProductCategory;
    private javax.swing.JButton btnProductCount;
    private javax.swing.JButton btnRequisition;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel dayLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage10;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblImage5;
    private javax.swing.JLabel lblImage6;
    private javax.swing.JLabel lblImage7;
    private javax.swing.JLabel lblImage8;
    private javax.swing.JLabel lblImage9;
    private javax.swing.JPanel pnlGrn;
    private javax.swing.JPanel pnlInvoice;
    private javax.swing.JPanel pnlPo;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlSystem;
    private javax.swing.JLabel timeLable;
    // End of variables declaration//GEN-END:variables

    private void getDateAndTime() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String formatedDate = dateFormat.format(date);
//        dateText.setText(formatedDate);

        Thread t1 = new Thread() {

            @Override
            public void run() {

                while (true) {
                    Date date = new Date();
                    SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss");
                    String FormatedTime = timeFormat.format(date);
                    timeLable.setText(FormatedTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        };
        t1.start();

    }

}
