/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.view.login;

import application.Dashbord.Dashbord;
import application.entity.UserLogin;
import application.controller.UserController;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Shashiprabha
 */
public class Login extends javax.swing.JFrame {
    

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
//        txtUsername.setOpaque(true);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnSignin = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        txtUserPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtUserPassword.setBorder(null);
        txtUserPassword.setOpaque(false);
        jPanel1.add(txtUserPassword);
        txtUserPassword.setBounds(610, 420, 330, 30);

        txtUsername.setBorder(null);
        txtUsername.setOpaque(false);
        jPanel1.add(txtUsername);
        txtUsername.setBounds(610, 360, 330, 30);

        btnSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-sing-in.png"))); // NOI18N
        btnSignin.setPreferredSize(new java.awt.Dimension(196, 42));
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignin);
        btnSignin.setBounds(760, 480, 196, 42);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button.png"))); // NOI18N
        jPanel1.add(lblBackground);
        lblBackground.setBounds(4, 0, 1024, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
//        Dashbord dashbord = new Dashbord();
//        dashbord.setVisible(true);
        List list = null;
        Session session = null;
        Query query = null;
        //PLEASE ADD SOME VALUES INTO UR DB UNDER THE UserLogin Table
        try {

            UserController userController = new UserController();
            UserLogin userLogin = new UserLogin();

            userLogin.setUserName(txtUsername.getText().trim());
            userLogin.setUserPassword(txtUserPassword.getText().trim());
            
            boolean status = userController.isUserExists(userLogin);

            if (status == true) {
                JOptionPane.showMessageDialog(null, "WELCOME ");
                Dashbord dashbord = new Dashbord();
                dashbord.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Login failed, Please Try Again");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Something wrong " + ex);
        }
    }//GEN-LAST:event_btnSigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtUserPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
