/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.po;

import application.controller.PoController;
import application.controller.PoDetailController;
import application.entity.Po;
import application.entity.SupplierItem;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Shashiprabha-PC
 */
public class POAccept1 extends javax.swing.JDialog {

    private DefaultTableModel modelPo;
    private SupplierItem supplierItem;
    private TableColumnModel tcmPo;
    private TableColumn colPoId;
    private PoController poController;
    private PoDetailController poDetailController;

    public POAccept1(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
       // checkBtnPo();

        supplierItem = new SupplierItem();
        poController = new PoController();
        poDetailController = new PoDetailController();

        modelPo = (DefaultTableModel) tblPo.getModel();

        poController.getAllPo(modelPo);

        tcmPo = tblPo.getColumnModel();
        hideColoumn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPo = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accept PO");
        setPreferredSize(new java.awt.Dimension(1000, 700));

        txtSearch.setMinimumSize(new java.awt.Dimension(256, 20));
        txtSearch.setPreferredSize(new java.awt.Dimension(256, 20));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        tblPo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "PO No", "Created At", "Updated At"
            }
        ));
        jScrollPane1.setViewportView(tblPo);

        btnAccept.setText("Accept ");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");

        btnDelete.setText("Discard");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAccept)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnAccept))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        if (tblPo.getRowCount() == 0 && tblPo.getModel().getRowCount() == 0) {

            txtSearch.requestFocus();

        } else {
            tblPo.requestFocus();
            tblPo.changeSelection(0, 0, false, false);
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelPo);
        tblPo.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearch.getText()));
        checkBtnPo();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        
        int row = tblPo.convertRowIndexToModel(tblPo.getSelectedRow());
        int poid = Integer.valueOf(modelPo.getValueAt(row, 0).toString());
        Po oldPo = poController.findPobyId(poid);
        Po po = new Po();
        po = oldPo;
        //po.setPo_id(0L);
       // PoType poType = new PoType();
        //poType.setPo_type_id(3);
        //po.setPoType(poType);
        Date date = new Date();
        po.setUpdatedAt(date);
        //po.setSyncStatus(0); // To be sync
        po.setApproveStatus("2");//Approve 
        poDetailController.savePoDetailDirectAccept(po);
        oldPo = poController.findPobyId(poid);
        //oldPo.setReferenceId((int) (long) po.getPo_id());
        boolean save = poController.save(oldPo);

        if (save) {

            //JOptionPane.showMessageDialog( "PO ACCEPTED", "Success Message", JOptionPane.INFORMATION_MESSAGE);
            poController.getAllPo(modelPo);
            //poController.getAllSpecialPriceDimoPo(modelPo_Special);
            //poController.getAllKitPromotionDimoPo(modelPo_Kit);
            checkBtnPo();

        } else {

            //JOptionPane.showMessageDialog(panel, "ERROR IN PO ACCEPTING", "Error Message", JOptionPane.ERROR_MESSAGE);
            checkBtnPo();
        }
        txtSearch.requestFocus();

    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int selectedRow = tblPo.convertRowIndexToModel(tblPo.getSelectedRow());
        long poId = Long.parseLong(modelPo.getValueAt(selectedRow, 0).toString());
        Po po = poController.findPobyId(poId);
        po.setDiscardStatus(1);
        po.setDeletedAt(new Date());
        boolean status = poController.update(po);
        if (status) {
            modelPo.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Purchase order discarded successfully", "Success Message", JOptionPane.INFORMATION_MESSAGE);
            //checkBtnDimoPo();
           // poController.getAllPo(modelPo);
        } else {
            JOptionPane.showMessageDialog(this, "Error in Purchase order discarding", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        txtSearch.requestFocus();

    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POAccept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POAccept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POAccept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POAccept1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                POAccept1 dialog = new POAccept1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void checkBtnPo() {
        if (tblPo.getSelectedRowCount() > 0) {
            btnDelete.setEnabled(true);
            btnEdit.setEnabled(true);
            btnAccept.setEnabled(true);
        } else {
            btnDelete.setEnabled(false);
            btnEdit.setEnabled(false);
            btnAccept.setEnabled(false);
        }

    }

    private void hideColoumn() {
        colPoId = tcmPo.getColumn(0);
        tcmPo.removeColumn(colPoId);

    }

}
