/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.forms.po;

import application.controller.MailController;
import application.controller.PoController;
import application.controller.PoDetailController;
import application.controller.ProductController;
import application.controller.SupplierController;
import application.controller.SupplierItemController;
import application.entity.Payment;
import application.entity.Po;
import application.entity.PoDetail;
import application.entity.SupplierItem;
import constructionsolution.ComboSearch;
import constructionsolution.NumbeFormater;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Shashiprabha
 */
public class PONew extends javax.swing.JDialog {

    private SupplierController supplierController;
    private PoController poController;
    private PoDetailController poDetailController;
    private SupplierItemController supplierItemController = null;

    private DefaultTableModel modelProduct;
    private DefaultTableModel modelPoItem;
    private TableColumnModel tcmPoItem;
    private TableColumn colProductId, colPoItemId;
    private ArrayList<String> productList;

    private POView pOView;

    public PONew(java.awt.Dialog parent, boolean modal, POView pOView) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        supplierController = new SupplierController();
        poController = new PoController();
        poDetailController = new PoDetailController();

        modelProduct = (DefaultTableModel) tblProduct.getModel();
        modelPoItem = (DefaultTableModel) tblPoItem.getModel();
        productList = new ArrayList<String>();

        //load product in to table 
        supplierItemController = new SupplierItemController();
        modelProduct = (DefaultTableModel) tblProduct.getModel();
        modelPoItem = (DefaultTableModel) tblPoItem.getModel();
        supplierItemController.getAllSupplierItems(modelProduct);

        TableColumnModel tcm = tblProduct.getColumnModel();
        TableColumn columnId = tcm.getColumn(0);
        tcm.removeColumn(columnId);

//        tcmPoItem = tblPoItem.getColumnModel();
//        colProductId = tcmPoItem.getColumn(0);
//        tcmPoItem.removeColumn(colProductId);
//        hideColumnOnTables();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProductSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtQuntity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPoItem = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add po");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        jLabel1.setText("Search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 33, 14);

        txtProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtProductSearch);
        txtProductSearch.setBounds(90, 30, 150, 20);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add PO"));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Description", "Manufactor", "UOM", "Supplier"
            }
        ));
        jScrollPane1.setViewportView(tblProduct);

        jLabel2.setText("Quntity");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuntity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuntity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 60, 910, 253);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove PO"));

        tblPoItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Description", "Manufacture", "UOM", "Supplier", "Qty"
            }
        ));
        jScrollPane2.setViewportView(tblPoItem);

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRemove)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRemove)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 340, 910, 314);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(880, 670, 57, 23);

        jButton2.setText("Send Mail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1070, 680, 77, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductSearchActionPerformed
        if (tblProduct.getRowCount() == 0 && tblProduct.getModel().getRowCount() == 0) {

            txtProductSearch.requestFocus();

        } else {
            tblProduct.requestFocus();
            tblProduct.changeSelection(0, 0, false, false);
        }
    }//GEN-LAST:event_txtProductSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MailController mailController = new MailController(this, rootPaneCheckingEnabled);
        mailController.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (tblProduct.getSelectedRow() > -1) {

            int selectedRow = tblProduct.convertRowIndexToModel(tblProduct.getSelectedRow());
            if (!NumbeFormater.isNumeric(txtQuntity.getText())) {
                JOptionPane.showMessageDialog(this, "Invalid Quntity.", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (Integer.parseInt(txtQuntity.getText()) < 1 && txtQuntity.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be Zero (0).", "Warning Message", JOptionPane.WARNING_MESSAGE);

            } else if (productList.contains(modelProduct.getValueAt(selectedRow, 0).toString())) {
                JOptionPane.showMessageDialog(this, "Product already Added.", "Error Message", JOptionPane.ERROR_MESSAGE);

            } else {

                int productId = Integer.valueOf(modelProduct.getValueAt(selectedRow, 0).toString());
                String productName = modelProduct.getValueAt(selectedRow, 1).toString();
                String manufacture = modelProduct.getValueAt(selectedRow, 2).toString();
                String uom = modelProduct.getValueAt(selectedRow, 3).toString();
                String supplier = modelProduct.getValueAt(selectedRow, 4).toString();
                //double buyingPrice = NumbeFormater.formatCleanString(tableModelRentalAdd.getValueAt(selectedRow, 3).toString());
                int qty = Integer.valueOf(txtQuntity.getText());

                productList.add(modelProduct.getValueAt(selectedRow, 0).toString());
                modelPoItem.addRow(new Object[]{productId, productName, manufacture, uom, supplier, qty});

                txtQuntity.setText("0");
                tblProduct.clearSelection();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Rental Product.", "Error Message", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedRow = tblPoItem.getSelectedRow();
        if (selectedRow > -1) {
            productList.remove(modelPoItem.getValueAt(selectedRow, 0).toString());
            modelPoItem.removeRow(tblPoItem.getSelectedRow());

        } else {
            JOptionPane.showMessageDialog(rootPane, "Select a row.", "Warning Message", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (tblPoItem.getRowCount() > 0) {

            Date date = new Date();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY-MM-dd");

            Po po = new Po();
            po.setCreatedAt(date);
            po.setStatus(true);
            po.setUpdatedAt(date);

            List<PoDetail> poDetails = new ArrayList<PoDetail>();

            for (int i = 0; i < tblPoItem.getRowCount(); i++) {
                System.out.println("iddddddddddddddd" + tblPoItem.getValueAt(i, 0));

                SupplierItem supplierItem = new SupplierItem();
                supplierItem.setSupplierItemId(Integer.parseInt(tblPoItem.getValueAt(i, 0).toString()));
                PoDetail po_Detail = new PoDetail();
                po_Detail.setProduct(supplierItem);
                po_Detail.setQty(Integer.parseInt(modelPoItem.getValueAt(i, 5).toString()));
                po_Detail.setCreatedAt(date);
                po_Detail.setUpdatedAt(date);
                po_Detail.setStatus(true);
                po.setPoDetails(poDetails);

            }

            boolean status = poController.savePoDetais(po);
            if (status) {
                JOptionPane.showMessageDialog(this, "PO added successfully.", "Success Message", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Error in adding RENTAL.", "Error Message", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "RENTAL must has at least one product.", "Warning Message", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PONew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PONew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PONew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PONew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PONew dialog = new PONew(new javax.swing.JDialog(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPoItem;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtProductSearch;
    private javax.swing.JTextField txtQuntity;
    // End of variables declaration//GEN-END:variables

    private void hideColumnOnTables() {

        tcmPoItem = tblPoItem.getColumnModel();
        colPoItemId = tcmPoItem.getColumn(0);
        tcmPoItem.removeColumn(colPoItemId);

    }

}
